In [146]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [147]:
months = {0:'January',1:'February',2:'March',3:'April',4:'May',5:'June',6:'July',7:'August',8:'September',
           9:'October',10:'November',11:'December'}

In [148]:
import numpy as np

In [149]:
#Revenue as numpy ndarray for faster calculations
revenue = np.array(revenue)

In [150]:
#Expenses as numpy array
expenses = np.array(expenses)

In [151]:
#Profit Calculation
Profit = revenue - expenses
Profit = Profit.astype(int)

In [152]:
#Profit After Tax Calculation
Profit_After_Tax = Profit - (Profit * 30 / 100)

#changing data type to integers
Profit_After_Tax = Profit_After_Tax.astype(int)

In [153]:
#Profit Margin Calculation (as % units) 
Profit_Margin = (Profit_After_Tax / revenue) * 100
Profit_Margin = Profit_Margin.astype(int)


In [160]:
#Mean Calculation of Profit After Tax
Profit_After_Tax_Mean = np.mean(Profit_After_Tax)

In [155]:
Good_Months = Profit_After_Tax > Profit_After_Tax_Mean

In [156]:
Bad_Months = Profit_After_Tax < Profit_After_Tax_Mean

In [157]:
BestMonth = max(Profit_After_Tax)

In [158]:
WorstMonth = min(Profit_After_Tax)

In [161]:
#Print Results
print ("Revenue :") 
print (revenue)
print ("Expenses :") 
print (expenses)
print ("Profit :")
print(Profit)
print ("Profit after tax :")
print (Profit_After_Tax)
print ("Profit margin :")
print (Profit_Margin)
print ("Good months :")
print (Good_Months)
print ("Bad months :")
print (Bad_Months)
print ("Best month :")
print (BestMonth)
print ("Worst month :")
print (WorstMonth)

Revenue :
[ 14574.49   7606.46   8611.41   9175.41   8058.65   8105.44  11496.28
   9766.09  10305.32  14379.96  10713.97  15433.5 ]
Expenses :
[ 12051.82   5695.07  12319.2   12089.72   8658.57    840.2    3285.73
   5821.12   6976.93  16618.61  10054.37   3803.96]
Profit :
[ 2522  1911 -3707 -2914  -599  7265  8210  3944  3328 -2238   659 11629]
Profit after tax :
[ 1765  1337 -2594 -2039  -419  5085  5747  2760  2329 -1566   461  8140]
Profit margin :
[ 12  17 -30 -22  -5  62  49  28  22 -10   4  52]
Good months :
[ True False False False False  True  True  True  True False False  True]
Bad months :
[False  True  True  True  True False False False False  True  True False]
Best month :
8140
Worst month :
-2594
